# Site
name: "illab"
title: "illab"
description: "illab Tech Blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
#google_analytics: 'UA-xxxxxxxx-1'
#disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: inje.illab@gmail.com

# Authors
# type : student(재학생), graduate(졸업생), professor(교수님)
authors:
  Dongmin:
    name: Dongmin
    display_name: "고동민"    
    avatar: "https://avatars.githubusercontent.com/u/50660440"
    #email: 
    web: https://coding-study00.tistory.com/
    # twitter: https://twitter.com/wowthemesnet
    github: https://github.com/Gdm0714
    # description: ""
    type: "student"
    
  Junhyeok:
    name: Junhyeok
    display_name: "전준혁"    
    avatar: "https://avatars.githubusercontent.com/u/65655340"
    # email: 
    # web: https://www.wowthemes.net
    # twitter: https://twitter.com/wowthemesnet
    github: https://github.com/Good-jjun
    #description: ""
    type: "student"

  Hyeona:
    name: Hyeona
    display_name: "당현아"    
    avatar: "https://avatars.githubusercontent.com/u/45550607"
    email: eona1301@gmail.com
    # web: https://www.wowthemes.net
    # twitter: https://twitter.com/wowthemesnet
    github: https://github.com/eona1301
    description: "공유의 가치를 추구하는 개발자"
    type: "graduate"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
